version: '3.7'

services:
  web:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    restart: unless-stopped
    container_name: nodejs
    stdin_open: true
    tty: true
    networks:
      - nodejss

volumes:
  db:
networks:
  nodejss:
